apiVersion: batch/v1
kind: Job
metadata:
  name: kor-once
  namespace: kor
spec:
  ttlSecondsAfterFinished: 60   # auto-clean after 1 minute
  template:
    spec:
      serviceAccountName: kor
      restartPolicy: Never
      containers:
      - name: kor
        image: yonahdissen/kor:latest
        args: ["all", "-v", "--show-reason", "--exclude-namespaces", "kube-system,kube-public,kor"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kor-read-all
rules:
  # Core resources
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "namespaces", "persistentvolumes"]
    verbs: ["get", "list", "watch"]

  # Workload controllers
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]

  # RBAC
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]

  # Networking
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies", "ingresses"]
    verbs: ["get", "list", "watch"]

  # Endpoint slices
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

  # Advanced network policies (admin/baseline)
  - apiGroups: ["policy.networking.k8s.io"]
    resources: ["adminnetworkpolicies", "baselineadminnetworkpolicies"]
    verbs: ["get", "list", "watch"]

  # CRDs themselves
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  # All Calico CRDs
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

  # (Optional) catch-all for any other CRDs kor tries to read
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kor-read-all-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kor-read-all
subjects:
  - kind: ServiceAccount
    name: kor
    namespace: kor
